base:
  project: mono-1-model-a
  dir_data_raw: ../data/raw
  dir_data_processed: ../data/processed
  dir_models: ../models
  dir_reports: ../reports
  random_state: 42 # random state for train/test split

data_load:
  dataset_csv: iris.csv

featurize:
  features_path: featured_iris.csv
  target_column: target

data_split:
  train_path: model-a-train_iris.csv
  test_path: model-a-test_iris.csv
  test_size: 0.3

train:
  model_name: model-a.joblib
  cv: 5
  estimator_name: logreg
  estimators:
    logreg: # sklearn.linear_model.LogisticRegression
      param_grid: # params of GridSearchCV constructor
        C: [0.01, 0.1]
        max_iter: [200]
        solver: ['lbfgs']
        multi_class: ['multinomial']

evaluate:
  metrics_file: model-a-metrics.json
  confusion_matrix_png: model-a-confusion_matrix.png
  plots_file: classess.csv
